project:
  type: website
  output-dir: docs

website:
  title: "Czech Vegetation Database"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    logo: ubz_logo_eng_2barvy.jpg
    logo-height: 50px
    logo-alt: "Botzool Logo"
    collapse-level: 2
    contents:

      - section: "About"
        href: index.qmd
        contents:
        - text: "Introduction"
          href: About/introduction.qmd
        - text: "Current state"
          href: About/current_state.qmd
        - text: "Turboveg for Windows"
          href: About/turboveg_windows.qmd
        - text: 'Acknowledgements'
          href: About/acknowledgements.qmd

      - section: "Data availability"
        href: DataAvailability/data_availability.qmd
        contents:
          - text: "CzechVeg-Open"
            href: DataAvailability/czech_veg_open.qmd
          - text: "CzechVeg-Open-Strat"
            href: DataAvailability/czech_veg_open_strat.qmd

      - section: "Data processing tutorial"
        href: DataProcessingTutorial/data_processing_tutorial.qmd
        contents:
          - text: "Turboveg to R"
            href: DataProcessingTutorial/turboveg_r.qmd
          - text: "Basic data analyses"
            href: DataProcessingTutorial/basic_analyses.qmd
          - text: "Export to other formats"
            href: DataProcessingTutorial/export.qmd
          - text: 'Data stratification'
            href: DataProcessingTutorial/data_stratification.qmd
          - text: 'Export to GBIF'
            href: DataProcessingTutorial/export_gbif.qmd


format:
  html:
    theme: cosmo
    toc: true

